### PR TITLE
Fixes #50

### LINKED ISSUE #50: Multiple footer rows export not working
When having more then one footer row in a MatTable, only the first one gets exported. 
I wanted to give a try on solving it, but after building mat-table-exporter/cdk-table-exporter using the steps from 'Contribute' section, when trying to use the library in my app, I get the following error:

ERROR in Failed to compile entry-point mat-table-exporter (es2015 as esm2015) due to compilation errors:
../mat-table-ext/node_modules/@angular/material/table/table-module.d.ts:8:22 - error NG6002: Appears in the NgModule.imports of MatTableExporterModule, but could not be resolved to an NgModule class

export declare class MatTableModule {

Any ideas on how to get the library working on my local environment, so I can try fixing the issue?

### PR DESCRIPTION
**Pull request by ccosmincc**
Fixes multiple headers/footers export.

### CODE REVIEW

**Comment by ccosmincc** [comment]
Introduces `selectedRows` functionality.

**Comment by HalitTalha** [comment]
👍 Thanks for the fix and selectedRows functionality.

Regarding selectedRows functionality, although I find the way you implemented it presents a more intuitive API, it makes clients obligated to calculate the selection's indexes. I would be in favor of doing it inside cdk-table-exporter, providing a `toggleRow(index: number)` method that's to be called on row selection event. Also a masterToggle() method seems to be nice in order to increase performance when the client wants all the rows selected. What would you think regarding those cases?

**template**
 ```
 <mat-table matTableExporter [dataSource]="dataSource" #exporter="matTableExporter" [hiddenColumns]="[0]" [exportSelection]="true">

  <!-- Checkbox Column -->
  <ng-container matColumnDef="select">
     <th mat-header-cell *matHeaderCellDef>
      <mat-checkbox (change)="$event ? masterToggle() : null"
                    [checked]="selection.hasValue() && isAllSelected()"
                    [indeterminate]="selection.hasValue() && !isAllSelected()"
                    [aria-label]="checkboxLabel()">
      </mat-checkbox>
    </th>
    <td mat-cell *matCellDef="let row; let i = index">
      <mat-checkbox (click)="$event.stopPropagation()"
                    (change)="$event ? toggleSelection(row, i) : null"
                    [checked]="selection.isSelected(row)"
                    [aria-label]="checkboxLabel(row)">
      </mat-checkbox>
    </td>
  </ng-container>
```

**ts**

masterToggle() {
     .... selectionModel related stuff
    this.exporter.masterToggle()
}

toggleSelection(row: any, i: number) {
    this.selection.toggleRow(row); // selection model related stuff
    this.exporter.toggleRow(i);
}

**Comment by ccosmincc** [comment]
I have done one more commit with the refactored functionality of selecting rows, based on your suggestion. The only thing I'm not really convinced about is the performance gains obtained by using that boolean flag versus the chattiness that it introduces in the code. This flag is useful only in this specific scenario: user wants to select all rows, in which case we by-pass filtering the rows against the array of selected rows. On the other hand, if user selects all rows via `masterToggle`, and then tries to deselect one row by using `toggleRow` there is logic around this boolean flag (as seen [here](https://github.com/HalitTalha/ng-material-extensions/pull/59/commits/0e0d93642a41f8865682301f2b218b82f031d9ab#diff-7e82f74844e9e181323ddc38a13ff7ceR102) or [here](https://github.com/HalitTalha/ng-material-extensions/pull/59/commits/0e0d93642a41f8865682301f2b218b82f031d9ab#diff-7e82f74844e9e181323ddc38a13ff7ceR111)). The only reason why I would see this flag there is if expected usages of this functionality are:
1. user selects a few rows
2. user selects all rows

The flag along with all logic related to it could be removed and the information could be determined, where required, based on the number of selected rows === total number of items in the table.

**Comment by HalitTalha** [comment]
Thanks for the contribution. You are totally right about the flag, I see I didn't think it through when I was writing the comment. It is not a tradeoff that I would like to take either.
I'm planning to ship your contributions as the new patch release by the end of this week. If you can not find the time to undo the flag part I can do it before the release. 👍

**Comment by ccosmincc** [comment]
I pushed the changes to remove the flag.

**Comment by ccosmincc** [comment]
Any updates on when will this be merged/released? Thanks!

**Comment by HalitTalha** [comment]
Will merge and release today along with my changes.

**Pull request merged**
