### PR TITLE
Feature/resetting selected rows

### PR DESCRIPTION
**Pull request by janakavishwajith**
Solution for the issue raised under https://github.com/HalitTalha/ng-material-extensions/issues/67

### CODE REVIEW

**Comment by HalitTalha** [comment]
https://github.com/HalitTalha/ng-material-extensions/pull/88#issuecomment-752226266

**Comment by janakavishwajith** [comment]
Hello @HalitTalha,
May I know why this got closed without merging to the master branch?
I think the change is a good addition to the library...

Regards,
Janaka

**Comment by HalitTalha** [comment]
Hello @janakavishwajith 
The underlying implementation will be changed with the upcoming major release, which currently I'm planning to make very soon. That's why this could be a short living commit. However we can still get it into the patch release of today.

**Comment by janakavishwajith** [comment]
Oh, is it?
It would be great if you can merge it for the patch release. 
So I can live on the patch for a while before moving to the new major update. Because, I'm not ready for a major update now.

Thanks,
Janaka

**Pull request merged**
